services:
  cake-mysql:
    platform: linux/x86_64
    image: mysql:8.0.23
    container_name: cake-mysql
    entrypoint: [ '/entrypoint.sh', '--default-authentication-plugin=mysql_native_password' ]
    hostname: cake-mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cake
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
      MYSQL_ROOT_PASSWORD: root
    command: [ "--log_bin_trust_function_creators=1" ]
    networks:
      - cake-network

  cake-nginx:
    platform: linux/arm64/v8
    image: nginx:latest
    container_name: webserver
    hostname: webserver
    restart: always
    tty: true
    depends_on:
      - cake-services
    ports:
      - "8080:8080"
    volumes:
      - .:/srv/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    networks:
      - cake-network

  cake-services:
    container_name: cake-services
    hostname: cake-services
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        - WITH_XDEBUG=false
#        - CI_ENV=dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/srv/app
    depends_on:
#      - pay-rabbitmq
#      - pay-redis
      - cake-mysql
#    volumes:
#      - .:/srv/app
    working_dir: /srv/app
    networks:
      - cake-network

networks:
  cake-network: